[package]
name = "pirrigator"
version = "0.1.0"
authors = ["Neil Gall <neilgall@mac.com>"]
edition = "2018"

[dependencies]
rusqlite = "0.17.0"
serde_derive = "^1.0.8"
serde = "^1.0.8"
config = "0.9.2"
sysfs_gpio = "0.5.3"
bme280 = { path = "../bme280" }
mcp3xxx = { path = "../mcp3xxx" }
