moisture: []
buttons: []
valves: []

database:
  path: "db.sqlite"
  
controller:
  irrigate_seconds: 60
  location:
    latitude: 55.9
    longitude: 3.297
  zones:
  - name: Tomatoes
    valve: Tomatoes
    sensors:
      - Cherry Tomatoes
      - Alicante Tomatoes
    target: 75
    check:
      - start: sunrise
        every: 30
        duration: 120

  - name: Courgettes
    valve: Courgettes
    sensors:
      - Courgettes
    target: 75
    check:
      - start: sunrise
        every: 30
        duration: 120
