[package]
name = "pirrigator-ui"
version = "0.1.0"
authors = ["Neil Gall <neilgall@mac.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.3.3"
wasm-bindgen = "0.2.43"
web-sys = "^0.3.19"
serde = "^1.0.8"
serde_derive = "^1.0.8"
futures = "^0.1.26"
chrono = "0.4.6"
