[package]
name = "pirrigator-ui"
version = "0.1.0"
authors = ["Neil Gall <neilgall@mac.com>"]
edition = "2018"

[dependencies]
draco = "0.1.0"
wasm-bindgen = "0.2.43"
serde = "^1.0.8"
serde_derive = "^1.0.8"
serde_json = "^1.0"